DROP TABLE if EXISTS account CASCADE;
DROP TABLE if EXISTS movie_group CASCADE;
DROP TABLE if EXISTS movie_mp4 CASCADE;
DROP TABLE if EXISTS movie_trailer CASCADE;
DROP TABLE if EXISTS movie CASCADE;
DROP TABLE if EXISTS user_profile CASCADE;
DROP TABLE if EXISTS common_lookup CASCADE;
DROP TABLE if EXISTS icon CASCADE;

